/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CultureRouteImport } from './routes/culture'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TechRouteImport } from './routes/tech'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WorldRouteImport } from './routes/world'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoute = CultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TechRoute = TechRouteImport.update({
  id: '/tech',
  path: '/tech',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/culture': typeof CultureRoute
  '/privacy': typeof PrivacyRoute
  '/tech': typeof TechRoute
  '/terms': typeof TermsRoute
  '/world': typeof WorldRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/culture': typeof CultureRoute
  '/privacy': typeof PrivacyRoute
  '/tech': typeof TechRoute
  '/terms': typeof TermsRoute
  '/world': typeof WorldRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/culture': typeof CultureRoute
  '/privacy': typeof PrivacyRoute
  '/tech': typeof TechRoute
  '/terms': typeof TermsRoute
  '/world': typeof WorldRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/business'
    | '/contact'
    | '/culture'
    | '/privacy'
    | '/tech'
    | '/terms'
    | '/world'
    | '/admin'
    | '/article/$slug'
    | '/api/public/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/business'
    | '/contact'
    | '/culture'
    | '/privacy'
    | '/tech'
    | '/terms'
    | '/world'
    | '/admin'
    | '/article/$slug'
    | '/api/public/ingest'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/business'
    | '/contact'
    | '/culture'
    | '/privacy'
    | '/tech'
    | '/terms'
    | '/world'
    | '/_authenticated/admin'
    | '/article/$slug'
    | '/api/public/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BusinessRoute: typeof BusinessRoute
  ContactRoute: typeof ContactRoute
  CultureRoute: typeof CultureRoute
  PrivacyRoute: typeof PrivacyRoute
  TechRoute: typeof TechRoute
  TermsRoute: typeof TermsRoute
  WorldRoute: typeof WorldRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture': {
      id: '/culture'
      path: '/culture'
      fullPath: '/culture'
      preLoaderRoute: typeof CultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech': {
      id: '/tech'
      path: '/tech'
      fullPath: '/tech'
      preLoaderRoute: typeof TechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BusinessRoute: BusinessRoute,
  ContactRoute: ContactRoute,
  CultureRoute: CultureRoute,
  PrivacyRoute: PrivacyRoute,
  TechRoute: TechRoute,
  TermsRoute: TermsRoute,
  WorldRoute: WorldRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
